spring:
  application:
    name: RxProducer
  devtools:
    add-properties: false
    restart:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /producer
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

springdoc.swagger-ui.path: /open-api/swagger-ui.html
springdoc.api-docs.enabled: true

logging:
  level:
    root: INFO

logging.level.org.springframework.web.reactive: DEBUG
logging.level.reactor.netty: DEBUG